apiVersion: apps/v1
kind: Deployment
metadata:
    name: hotel
spec:
    replicas: 1
    selector:
        matchLabels:
            app: hotel
    template:
        metadata:
            labels:
                app: hotel
        spec:
            containers:
                - name: hotel
                  image: hotel:latest
                  ports:
                      - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
    name: hotel
spec:
    selector:
        app: hotel
    ports:
        - protocol: TCP
          port: 80
          targetPort: 5000
