apiVersion: apps/v1
kind: Deployment
metadata:
    name: payment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: payment
    template:
        metadata:
            labels:
                app: payment
        spec:
            containers:
                - name: payment
                  image: payment:latest
                  ports:
                      - containerPort: 8080
                  env:
                      - name: ASPNETCORE_URLS
                        value: "http://+:8080"

---
apiVersion: v1
kind: Service
metadata:
    name: payment
spec:
    selector:
        app: payment
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8080
