// Code generated by mockery v2.47.0. DO NOT EDIT.

package queue

import (
	context "context"
	models "device-readings/internal/readings/models"

	mock "github.com/stretchr/testify/mock"
)

// MockProducer is an autogenerated mock type for the Producer type
type MockProducer struct {
	mock.Mock
}

type MockProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProducer) EXPECT() *MockProducer_Expecter {
	return &MockProducer_Expecter{mock: &_m.Mock}
}

// Write provides a mock function with given fields: ctx, batch
func (_m *MockProducer) Write(ctx context.Context, batch []models.BatchReading) error {
	ret := _m.Called(ctx, batch)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.BatchReading) error); ok {
		r0 = rf(ctx, batch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProducer_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockProducer_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - ctx context.Context
//   - batch []models.BatchReading
func (_e *MockProducer_Expecter) Write(ctx interface{}, batch interface{}) *MockProducer_Write_Call {
	return &MockProducer_Write_Call{Call: _e.mock.On("Write", ctx, batch)}
}

func (_c *MockProducer_Write_Call) Run(run func(ctx context.Context, batch []models.BatchReading)) *MockProducer_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]models.BatchReading))
	})
	return _c
}

func (_c *MockProducer_Write_Call) Return(_a0 error) *MockProducer_Write_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProducer_Write_Call) RunAndReturn(run func(context.Context, []models.BatchReading) error) *MockProducer_Write_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProducer creates a new instance of MockProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProducer {
	mock := &MockProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
