def debezium():
    k8s_yaml('k8s/debezium.yaml')
    k8s_resource('debezium', port_forwards=8083, resource_deps=['postgres', 'redpanda'])

def debezium_create_connector():
    current_dir = os.path.dirname(__file__)

    docker_build('debezium-create-connector', current_dir, dockerfile_contents=CURL_DOCKERFILE)

    k8s_yaml(blob(JOB_YAML))
    k8s_resource('debezium-create-connector', resource_deps=['debezium'])

CURL_DOCKERFILE = """
FROM curlimages/curl:7.78.0
COPY create_connector.sh create_connector.sh
CMD ["sh", "/create_connector.sh"]
"""

JOB_YAML = """
apiVersion: batch/v1
kind: Job
metadata:
  name: debezium-create-connector
spec:
  template:
    spec:
      containers:
      - name: debezium-create-connector
        image: debezium-create-connector
      restartPolicy: Never
  backoffLimit: 4
"""