// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateReservationInput struct {
	CheckInDate  string `json:"checkInDate"`
	CheckOutDate string `json:"checkOutDate"`
	RoomTypeID   int    `json:"roomTypeId"`
	Quantity     int    `json:"quantity"`
	HotelID      int    `json:"hotelId"`
}

type Guest struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
	Phone string `json:"phone"`
}

type Mutation struct {
}

type Payment struct {
	ID       string  `json:"id"`
	Amount   float64 `json:"amount"`
	Currency string  `json:"currency"`
	Status   string  `json:"status"`
}

type Query struct {
}

type Reservation struct {
	ID         string   `json:"id"`
	Quantity   int      `json:"quantity"`
	CheckIn    string   `json:"checkIn"`
	CheckOut   string   `json:"checkOut"`
	Status     string   `json:"status"`
	RoomTypeID int      `json:"roomTypeId"`
	HotelID    int      `json:"hotelId"`
	PaymentID  int      `json:"paymentId"`
	GuestID    int      `json:"guestId"`
	RoomType   string   `json:"roomType"`
	Guest      *Guest   `json:"guest"`
	Payment    *Payment `json:"payment,omitempty"`
	CreatedAt  string   `json:"createdAt"`
}
