// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type Reservation struct {
	ID           string `json:"id"`
	GuestName    string `json:"guestName"`
	CheckInDate  string `json:"checkInDate"`
	CheckOutDate string `json:"checkOutDate"`
	RoomType     string `json:"roomType"`
}
