apiVersion: apps/v1
kind: Deployment
metadata:
  name: readings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: readings
  template:
    metadata:
      labels:
        app: readings
    spec:
      containers:
      - name: readings
        image: readings-image:latest
---
apiVersion: v1
kind: Service
metadata:
  name: readings
spec:
  selector:
    app: readings
  ports:
  - name: readings
    port: 8080
    targetPort: 8080
