v1alpha1.extension_repo('eb', url='https://github.com/ericbutera/tilt')

v1alpha1.extension(name='go_helper', repo_name='eb', repo_path='extensions/go_helper')
load('ext://go_helper', 'go_compile', 'go_image', 'go_service')

go_compile('api-compile', './cmd/api', ['./cmd/api'])
go_image('api', './cmd/api')

docker_build('k6', 'k6')

k8s_yaml(helm("helm"))
k8s_resource('k6', trigger_mode=TRIGGER_MODE_MANUAL, auto_init=False, resource_deps=['api'])
